package com.winterchen.dao;

import com.winterchen.model.SysRoleApi;
import com.winterchen.model.SysRoleApiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleApiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_api
     *
     * @mbg.generated
     */
    long countByExample(SysRoleApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_api
     *
     * @mbg.generated
     */
    int deleteByExample(SysRoleApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_api
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_api
     *
     * @mbg.generated
     */
    int insert(SysRoleApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_api
     *
     * @mbg.generated
     */
    int insertSelective(SysRoleApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_api
     *
     * @mbg.generated
     */
    List<SysRoleApi> selectByExample(SysRoleApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_api
     *
     * @mbg.generated
     */
    SysRoleApi selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_api
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysRoleApi record, @Param("example") SysRoleApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_api
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysRoleApi record, @Param("example") SysRoleApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_api
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysRoleApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_api
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysRoleApi record);
}