spring:
  redis:
           host: 127.0.0.1
           port: 6379
           timeout: 20000      #连接超时时间(ms)
           pool:
             max-active: 8     #连接池最大连接数(负数表示无限制)
             min-adle: 0
             max-idle: 8        #连接池中的最大空闲连接数
             max-wait: -1       #连接池最大阻塞等待时间(ms)(负数表示无限制)

  #session.store-type : redis