server:
  port: 8088

  servlet:
    session:
      timeout: "PT10M"     # session有效时长为10分钟


spring:
    datasource:
      db1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        #基本属性
        #jdbc-url: jdbc:mysql://127.0.0.1:3306/springboottest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT&useSSL=false      #localhost
        jdbc-url: jdbc:mysql://47.106.159.60:3306/springboottest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT&useSSL=false  #aliyunReal
        #jdbc-url: jdbc:mysql://192.168.43.182:3306/springboottest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT&useSSL=false  #vmware
        username: root
        password: root
        #password: shiyi261128   #vmware时密码换了
        initial-size: 5
        max-idle: 10
        max-wait: 10000
        min-idle: 5
      db2:
        driver-class-name: com.mysql.cj.jdbc.Driver
        #基本属性
        #jdbc-url: jdbc:mysql://127.0.0.1:3306/springboottest1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT&useSSL=false     #localhost
        jdbc-url: jdbc:mysql://47.106.159.60:3306/springboottest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT&useSSL=false  #aliyunReal
        #jdbc-url: jdbc:mysql://192.168.43.182:3306/springboottest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT&useSSL=false  #vmware
        username: root
        password: root
        #password: shiyi261128
        initial-size: 5
        max-idle: 10
        max-wait: 10000
        min-idle: 5

    profiles:
        include: redis,rabbitMQ
    cache:
        #ehcache配置文件路径
        ehcache:
          config: classpath:/encache/encache.xml
        #指定缓存类型，可加可不加
        #type: ehcache


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.winterchen.model  # 注意：对应实体类的路径

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

swagger:
    enable: true

easemob:
   host: http://a1.easemob.com/
   orgName: 1113190505010089
   appName: joyzone
   grantType: client_credentials
   clientId: YXA6eWR-kG9AEemCpmWWikCXLA
   clientSecret: YXA6XYMzIlVp-y-0BcbYbuxQC1nbDCg

ali:
  oss:
    secretId: LTAI4FhPLUnfs3buVqXJxe86
    secretKey: YpWzyGQsJOEeqrVSiLkOVEnRNgbBgi
    bucket: 9da
    domain: oss-cn-shenzhen.aliyuncs.com
  sms:
    codeTemplateCode: SMS_173348940
    signName: 九达缘起

fileSize: 2048000
scale: 0.8