package com.winterchen.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_role_api
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysRoleApi implements Serializable {
    /**
     * Database Column Remarks:
     *   主鍵
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_api.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   角色id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_api.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     * Database Column Remarks:
     *   api接口名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_api.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   api接口路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_api.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * Database Column Remarks:
     *   是否是叶子节点 0否 1是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_api.is_leaf
     *
     * @mbg.generated
     */
    private Integer isLeaf;

    /**
     * Database Column Remarks:
     *   删除状态 0正常 1已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_api.del_flag
     *
     * @mbg.generated
     */
    private Integer delFlag;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_api.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_api.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_api.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_api.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role_api
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_api.id
     *
     * @return the value of sys_role_api.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_api.id
     *
     * @param id the value for sys_role_api.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_api.role_id
     *
     * @return the value of sys_role_api.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_api.role_id
     *
     * @param roleId the value for sys_role_api.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_api.name
     *
     * @return the value of sys_role_api.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_api.name
     *
     * @param name the value for sys_role_api.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_api.url
     *
     * @return the value of sys_role_api.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_api.url
     *
     * @param url the value for sys_role_api.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_api.is_leaf
     *
     * @return the value of sys_role_api.is_leaf
     *
     * @mbg.generated
     */
    public Integer getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_api.is_leaf
     *
     * @param isLeaf the value for sys_role_api.is_leaf
     *
     * @mbg.generated
     */
    public void setIsLeaf(Integer isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_api.del_flag
     *
     * @return the value of sys_role_api.del_flag
     *
     * @mbg.generated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_api.del_flag
     *
     * @param delFlag the value for sys_role_api.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_api.create_by
     *
     * @return the value of sys_role_api.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_api.create_by
     *
     * @param createBy the value for sys_role_api.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_api.create_time
     *
     * @return the value of sys_role_api.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_api.create_time
     *
     * @param createTime the value for sys_role_api.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_api.update_by
     *
     * @return the value of sys_role_api.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_api.update_by
     *
     * @param updateBy the value for sys_role_api.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_api.update_time
     *
     * @return the value of sys_role_api.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_api.update_time
     *
     * @param updateTime the value for sys_role_api.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}