package com.winterchen.model;

import cn.afterturn.easypoi.excel.annotation.Excel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

@Table(name = SysUser.TABLE_NAME)
@ApiModel("用户信息")
public class SysUser implements Serializable {

    protected static final String TABLE_NAME = "sys_user";

    @Id
    @ApiModelProperty("主键")
    private Long id;

    @Column(name = "user_name")
    @ApiModelProperty("用户名称")
    @Excel(name="用户名称")
    private String userName;

    @ApiModelProperty("用户密码")
    @Excel(name="用户密码")
    private String password;

    @ApiModelProperty("手机号")
    @Excel(name="手机号")
    private String phone;

    @ApiModelProperty("环信注册用户时用useridMD5生成的密码")
    @Excel(name="环信注册用户时用useridMD5生成的密码")
    private String chatIdMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_name
     *
     * @return the value of sys_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_name
     *
     * @param userName the value for sys_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getChatIdMd5() {
        return chatIdMd5;
    }

    public void setChatIdMd5(String chatIdMd5) {
        this.chatIdMd5 = chatIdMd5;
    }


}